spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8885

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka/
    register-with-eureka: true
    fetch-registry: true

