server:
  port: 8881

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notify/**

    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka
