pipeline {
  agent any

  tools {
    jdk 'JDK8'
    maven 'Maven3'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        sh 'mvn -DskipTests package'
      }
    }
  }
}

